#! -*- coding: utf-8 -*-


class EventType(object):
    CHECKING = 'CHECKING'
    ALERTING = 'ALERTING'
    UPLOADING = 'UPLOADING'
    DOWNLOADING = 'DOWNLOADING'
    DOWNLOADING_FIRMWARE = 'DOWNLOADING_FIRMWARE'
    DOWNLOADING_RELEASENOTE = 'DOWNLOADING_RELEASENOTE'
